### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by agentofuser** [hashify/hashify.me#8]
Hi! Thank you for publishing Hashify, it is a great tool! I don't know if it is still being maintained, but I'd like to suggest adding support for HTTPS so it's possible to open links without a warning message. Thank you.

**Comment by davidchambers** [comment]
Good idea, @agentofuser. I have switched to HTTPS. Please close this issue if HTTPS works for you. :)

**Comment by agentofuser** [comment]
Thank you! It works perfectly.

**Comment by davidchambers** [comment]
Excellent. Thank you for the suggestion. :)
